galaxy_info:
  author: your name
  description: your description
  company: your company (optional)

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.4


  galaxy_tags: []

dependencies: []

